server:
  port: 9001
spring:
  application:
    name: eurekaServer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
#      defaultZone: http://localhost:9003/eurake/,http://localhost:9002/eureka/   
